Repository apache/maven-enforcer, pull requests merged in 2022-12, with the labels that each got.

#192 remove specific IDE m2e files
  maven-enforcer-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Labels: removed

#199 Add test for confirmation of failed bannedPlugins
  maven-enforcer-plugin/src/it/projects/banned-plugins-fails/invoker.properties
  maven-enforcer-plugin/src/it/projects/banned-plugins-fails/pom.xml
  maven-enforcer-plugin/src/it/projects/banned-plugins-fails/verify.groovy
Labels: maintenance

#202 [MENFORCER-435] Remove not needed maven-dependency-tree and maven-compat
  enforcer-rules/pom.xml
  maven-enforcer-plugin/pom.xml
  pom.xml
Labels: removed

#203 [MENFORCER-450] Code cleanup
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/AlwaysPass.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BanDependencyManagementScope.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BanDuplicatePomDependencyVersions.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BanDynamicVersions.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BanTransitiveDependencies.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/EnforcerExpressionEvaluator.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/EvaluateBeanshell.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/ReactorModuleConvergence.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireFileChecksum.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequirePluginVersions.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequirePrerequisite.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireSameVersions.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/utils/ArtifactMatcher.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/utils/DependencyVersionMap.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/utils/NormalizeLineSeparatorReader.java
  enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/BanDependencyManagementScopeTest.java
  enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/utils/MockEnforcerExpressionEvaluator.java
  enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/utils/TestArtifactMatcher.java
  enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/utils/TestMockEnforcerExpressionEvaluator.java
  maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/DisplayInfoMojo.java
  maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java
Labels: maintenance

#204 [MENFORCER-451] Refresh download page
  src/site/xdoc/download.xml.vm
Labels: maintenance

#206 [MENFORCER-452] Manage all Maven Core dependencies as provided
  enforcer-rules/pom.xml
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BanTransitiveDependencies.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BannedDependenciesBase.java
  maven-enforcer-extension/pom.xml
  maven-enforcer-plugin/pom.xml
  pom.xml
Labels: maintenance

#213 [MENFORCER-445] Include JAVA_HOME location in the Java rule failure messages
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireJavaVendor.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireJavaVersion.java
  enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireJavaVendor.java
  enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireJavaVersion.java
Labels: enhancement
