Repository apache/maven-enforcer, pull requests merged in 2023-03, with the labels that each got.

#246 [MENFORCER-470] AdvancedDependencyConvergence rule
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/DependencyConvergence.java
  enforcer-rules/src/site/apt/dependencyConvergence.apt.vm
Labels: enhancement

#253 [MENFORCER-469] Fix banTransitiveDependencies and transitive dependen…
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/BannedDependenciesBase.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/DependencyConvergence.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/RequireUpperBoundDeps.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/ResolveUtil.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/BannedDependenciesTest.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/RequireReleaseDepsTest.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/RequireUpperBoundDepsTest.java
  maven-enforcer-plugin/src/it/projects/ban-transitive-dependencies-direct-dep1/pom.xml
  maven-enforcer-plugin/src/it/projects/ban-transitive-dependencies-direct-dep2/pom.xml
  maven-enforcer-plugin/src/it/projects/ban-transitive-dependencies-direct-dep3/pom.xml
Labels: bug

#257 [MENFORCER-465] Remove superfluous blanks in BanDuplicatePomDependencyVersions
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/BanDuplicatePomDependencyVersions.java
  maven-enforcer-plugin/src/it/projects/ban-duplicate-dependencies-versions/verify.groovy
  maven-enforcer-plugin/src/it/projects/ban-pom-dependency-version-utf8-with-bom/verify.groovy
  maven-enforcer-plugin/src/it/projects/ban-pom-dependency-version/verify.groovy
Labels: maintenance

#256 [MENFORCER-474] Filter dependency by scope on project level
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/BannedDependenciesBase.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/DependencyConvergence.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/RequireUpperBoundDeps.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/ResolveUtil.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/selector/AllLevelsOptionalDependencySelector.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/selector/AllLevelsScopeDependencySelector.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/BannedDependenciesTest.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/RequireReleaseDepsTest.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/RequireUpperBoundDepsTest.java
Labels: bug

#261 [MENFORCER-276] Allow ignoring dependency scopes in RequireUpperBoundDeps
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/RequireUpperBoundDeps.java
  enforcer-rules/src/site/apt/requireUpperBoundDeps.apt.vm
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/RequireUpperBoundDepsTest.java
  maven-enforcer-plugin/src/it/mrm/repository/menforcer138_container-default-1.0-alpha-9-stable-1.pom
  maven-enforcer-plugin/src/it/mrm/repository/menforcer138_utils-1.0.4.pom
  maven-enforcer-plugin/src/it/projects/require-upper-bound-dependencies-scope-change/invoker.properties
  maven-enforcer-plugin/src/it/projects/require-upper-bound-dependencies-scope-change/pom.xml
  maven-enforcer-plugin/src/it/projects/require-upper-bound-dependencies-scope-change/verify.groovy
Labels: enhancement

#262 [MENFORCER-467] banDynamicVersions excludedScopes on project level
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/BanDynamicVersions.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/ResolverUtil.java
  maven-enforcer-plugin/src/it/projects/ban-dynamic-versions/verify.groovy
Labels: bug

#263 [MENFORCER-472] Install maven-enforcer-plugin for ITs in maven-enforcer-extension
  maven-enforcer-extension/pom.xml
Labels: maintenance
