Repository apache/maven-enforcer, pull requests merged in 2023-01, with the labels that each got.

#218 [MENFORCER-444] Improve error message for failed version rules
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/AbstractVersionEnforcer.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireJavaVersion.java
  enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireJavaVersion.java
Labels: enhancement

#221 [MENFORCER-407] Regression for dependencyConvergence - transitive provided
  maven-enforcer-plugin/src/it/projects/dependency-convergence_transitive_provided/module1/pom.xml
  maven-enforcer-plugin/src/it/projects/dependency-convergence_transitive_provided/module2/pom.xml
  maven-enforcer-plugin/src/it/projects/dependency-convergence_transitive_provided/pom.xml
  maven-enforcer-plugin/src/it/projects/dependency-convergence_transitive_provided/verify.groovy
Labels: bug

#222 [MENFORCER-378] Regression for non existing optional dependency
  maven-enforcer-plugin/src/it/projects/non-exeisting-optional-dependency/pom.xml
  maven-enforcer-plugin/src/it/projects/non-exeisting-optional-dependency/verify.groovy
Labels: bug

#223 [MENFORCER-434] Regression bannedDependencies - matching with not existing versions
  maven-enforcer-plugin/src/it/projects/MENFORCER-434/invoker.properties
  maven-enforcer-plugin/src/it/projects/MENFORCER-434/pom.xml
  maven-enforcer-plugin/src/it/projects/MENFORCER-434/verify.groovy
Labels: bug

#224 [MENFORCER-447] Skip tests for banDuplicatePomDependencyVersions and requireProfileIdsExist with Maven 4
  maven-enforcer-plugin/src/it/projects/ban-duplicate-dependencies-versions/invoker.properties
  maven-enforcer-plugin/src/it/projects/ban-pom-dependency-version-utf8-with-bom/invoker.properties
  maven-enforcer-plugin/src/it/projects/ban-pom-dependency-version/invoker.properties
  maven-enforcer-plugin/src/it/projects/require-plugin-versions-expressions2/pom.xml
  maven-enforcer-plugin/src/it/projects/require-profile-ids-exist_failure/invoker.properties
Labels: maintenance

#225 [MENFORCER-447] RequireNoRepositories skip repositories defined in settings.xml
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireNoRepositories.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/TestRequireNoRepositories.java
  maven-enforcer-plugin/src/it/projects/require-no-repositories/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-no-repositories_mm/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-no-repositories_mm_ci/verify.groovy
Labels: maintenance

#227 [MENFORCER-458] Move RequireOS to new API
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireOS.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/utils/OSUtil.java
  enforcer-rules/src/site/apt/requireOS.apt.vm
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/TestRequireOS.java
  maven-enforcer-plugin/src/it/projects/require-os/pom.xml
  maven-enforcer-plugin/src/it/projects/require-os/verify.groovy
  maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/DisplayInfoMojo.java
Labels: enhancement

#231 [MENFORCER-458] Move Require Property,Environment to new API
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/property/AbstractPropertyEnforcerRule.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/property/RequireEnvironmentVariable.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/property/RequireProperty.java
  enforcer-rules/src/site/apt/requireEnvironmentVariable.apt.vm
  enforcer-rules/src/site/apt/requireProperty.apt.vm
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/property/TestRequireEnvironmentVariable.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/property/TestRequireProperty.java
  maven-enforcer-plugin/src/it/projects/require-environment-variable/pom.xml
  maven-enforcer-plugin/src/it/projects/require-environment-variable/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-property/verify.groovy
Labels: enhancement

#232 [MENFORCER-458] Move Require Java, Maven Version to new API
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/utils/ArtifactMatcher.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/version/AbstractVersionEnforcer.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/version/RequireJavaVersion.java
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/version/RequireMavenVersion.java
  enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireMavenVersion.java
  enforcer-rules/src/site/apt/requireJavaVersion.apt.vm
  enforcer-rules/src/site/apt/requireMavenVersion.apt.vm
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/utils/TestArtifactMatcher.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/version/TestAbstractVersionEnforcer.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/version/TestMavenVersion.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/version/TestRequireJavaVersion.java
  enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestAbstractVersionEnforcer.java
  maven-enforcer-plugin/src/it/projects/require-java-version/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-maven-version/verify.groovy
  maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/DisplayInfoMojo.java
Labels: enhancement

#239 [MENFORCER-415] Move error message to MojoException
  maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java
Labels: enhancement

#241 [MENFORCER-462] Execute ReactorModuleConvergence only once
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/ReactorModuleConvergence.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/ReactorModuleConvergenceTest.java
Labels: bug

#242 [MENFORCER-463] Change success message from executed to passed
  maven-enforcer-plugin/src/it/projects/always-pass/verify.groovy
  maven-enforcer-plugin/src/it/projects/ban-distribution-management/verify.groovy
  maven-enforcer-plugin/src/it/projects/dependency-convergence_transitive_provided/verify.groovy
  maven-enforcer-plugin/src/it/projects/evaluate-beanshell/verify.groovy
  maven-enforcer-plugin/src/it/projects/external-rules-always-pass/verify.groovy
  maven-enforcer-plugin/src/it/projects/non-exeisting-optional-dependency/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-environment-variable/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-file-checksum/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-files-dont-exist/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-files-exist/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-files-size/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-java-vendor-multi-module/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-java-version/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-maven-version/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-no-repositories/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-no-repositories_mm/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-no-repositories_mm_ci/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-os/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-property/verify.groovy
  maven-enforcer-plugin/src/it/projects/require-textfile-checksum/verify.groovy
  maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java
  maven-enforcer-plugin/src/test/java/org/apache/maven/plugins/enforcer/TestEnforceMojo.java
Labels: enhancement
