Repository apache/maven-enforcer, pull requests merged in 2025-06, with the labels that each got.

#370 Make documentation explicit about java versions for custom rules
  enforcer-api/src/site/apt/writing-a-custom-rule.apt.vm
Labels: documentation

#892 `RequireSameVersions` rule: consider entries in `<plugins>` when analyzing build- and report-plugins
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireSameVersions.java
  enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/TestRequireSameVersions.java
  maven-enforcer-plugin/src/it/projects/require-same-versions_failure/verify.groovy
Labels: bug

#889 Update site descriptor to 2.0.0
  enforcer-api/src/site/site.xml
  enforcer-rules/src/site/site.xml
  maven-enforcer-extension/src/site/site.xml
  maven-enforcer-plugin/src/site/site.xml
  src/site/site.xml
Labels: maintenance

#893 Introduce ruleName for rules configuration
  enforcer-api/src/main/java/org/apache/maven/enforcer/rule/api/AbstractEnforcerRule.java
  enforcer-api/src/main/java/org/apache/maven/enforcer/rule/api/EnforcerRuleBase.java
  enforcer-rules/src/site/apt/alwaysPass.apt.vm
  enforcer-rules/src/site/apt/index.apt
  maven-enforcer-plugin/src/it/projects/always-fail-warn/pom.xml
  maven-enforcer-plugin/src/it/projects/always-fail-warn/verify.groovy
  maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/internal/EnforcerRuleDesc.java
Labels: enhancement

#890 Improve example of custom rule
  enforcer-api/src/custom-rule-sample/pom.xml
  enforcer-api/src/custom-rule-sample/src/main/java/org/example/custom/rule/MyCustomRule.java
Labels: documentation

#894 Warning about old enforcer api in rule implementation
  maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/internal/EnforcerRuleManager.java
Labels: enhancement
