Repository apache/maven-enforcer, pull requests merged in 2025-09, with the labels that each got.

#928 Fix formatting typo in dependencyConvergence.apt.vm
  enforcer-rules/src/site/apt/dependencyConvergence.apt.vm
Labels: documentation

#930 Use SessionData for cache storage
  maven-enforcer-plugin/src/it/projects/require-java-vendor-multi-module/invoker.properties
  maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/internal/EnforcerRuleCache.java
Labels: bug

#921 Fixes #920 - Remove usage of Stack
  enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/utils/ParentsVisitor.java
Labels: java, maintenance

#926 Update Version Ranges link in site.xml
  enforcer-rules/src/site/apt/versionRanges.apt
  maven-enforcer-plugin/src/site/site.xml
Labels: documentation

#935 Bump m-invoker-p to 3.9.1
  pom.xml
Labels: dependencies
